const BRICK_ZONA = {
  "5138": "IBAGUE",
  "5217": "IBAGUE",
  "5218": "IBAGUE",
  "5219": "IBAGUE",
  "5220": "IBAGUE",
  "5221": "IBAGUE",
  "8809": "CHICO COLSANITAS",
  "8810": "CHICO",
  "8811": "RINCON DEL CHICO",
  "8814": "CHICO",
  "8815": "CHICO",
  "8818": "CHICO LOS NOGALES",
  "8819": "CHICO TORRE ESPECIALISTAS",
  "8824": "LA CASTELLANA",
  "8825": "PARALELA 103",
  "9004": "CONTADOR",
  "9005": "CEDRITOS",
  "9006": "CEDRITOS 2",
  "9007": "CEDRITOS",
  "9012": "SANTA BARBARA CENTRAL",
  "9013": "SANTA BARBARA OCCIDENTAL",
  "9014": "LA CAROLINA",
  "9018": "REINA SOFIA",
  "9019": "REINA SOFIA",
  "9020": "BULEVAR NIZA",
  "9022": "CEDRITOS-COLINA",
  "9024": "CEDRITOS NORTE",
  "9025": "CEDRITOS-COLINA",
  "9026": "COLSANITAS CEDROBOLIVAR",
  "9027": "LA CARDIO",
  "9028": "TOBERIN",
  "9103": "CIUDAD JARDIN NORTE",
  "9104": "LA COLINA",
  "9114": "SUBA",
  "9117": "SUBA"
};

const PANEL_DATA = {
  "medicos": [
    {
      "origenId": "14297580",
      "nombre": "Rodríguez Arciniegas, Douglas Eduardo",
      "especialidad": "Medicina interna",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "IBAGUÉ",
      "brick": "5219",
      "brickZona": "IBAGUE",
      "direccion": "Calle 27 Sur #21A-19",
      "celular": "3167573183",
      "email": "douglas_eduard@hotmail.com",
      "deblax": false
    },
    {
      "origenId": "51991881",
      "nombre": "Acosta Rodríguez, Nohora Arlene",
      "especialidad": "Medicina interna",
      "segmento": "H,PS",
      "frecuencia": 2,
      "ciudad": "BOGOTÁ",
      "brick": "8809",
      "brickZona": "CHICO COLSANITAS",
      "direccion": "Carrera 14 #96-22",
      "celular": "3132520857",
      "email": "nohora_acosta@yahoo.com",
      "deblax": false
    },
    {
      "origenId": "75074406",
      "nombre": "Bedoya Ossa, Andrés",
      "especialidad": "Endocrinología, Diabetes y Metabolismo",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "8809",
      "brickZona": "CHICO COLSANITAS",
      "direccion": "Calle 93B #17-12",
      "celular": "3177666171",
      "email": "abedoyaossa@gmail.com",
      "deblax": false
    },
    {
      "origenId": "1045676657",
      "nombre": "De La Hoz Bilbao, Juan Manuel",
      "especialidad": "Medicina interna",
      "segmento": "E",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "8809",
      "brickZona": "CHICO COLSANITAS",
      "direccion": "Carrera 14 #96-22",
      "celular": "3219623730",
      "email": "juandelahoz_88@hotmail.com",
      "deblax": false
    },
    {
      "origenId": "1018440920",
      "nombre": "Estupiñán López, María Camila",
      "especialidad": "Cardiología",
      "segmento": "C",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "8809",
      "brickZona": "CHICO COLSANITAS",
      "direccion": "Carrera 14 #96-22",
      "celular": "3013719487",
      "email": "mcestupinanl@gmail.com",
      "deblax": false
    },
    {
      "origenId": "30336527",
      "nombre": "Forero Castelblanco, Mary Yommara",
      "especialidad": "Endocrinología, Diabetes y Metabolismo",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "8809",
      "brickZona": "CHICO COLSANITAS",
      "direccion": "Carrera 14 #96-22",
      "celular": "3134225552",
      "email": "yommyforero@outlook.com",
      "deblax": false
    },
    {
      "origenId": "1067866872",
      "nombre": "Kerguelen Villadiego, Alfonso Luis",
      "especialidad": "Endocrinología, Diabetes y Metabolismo",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "8809",
      "brickZona": "CHICO COLSANITAS",
      "direccion": "Calle 96 #13A-44",
      "celular": "3043534210",
      "email": "alfonso_k31088@hotmail.com",
      "deblax": false
    },
    {
      "origenId": "1095949815",
      "nombre": "Pineda Martínez, Ana Cecilia",
      "especialidad": "Medicina interna",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "8809",
      "brickZona": "CHICO COLSANITAS",
      "direccion": "Autopista Norte #103B-03",
      "celular": "3173668581",
      "email": "anapineda@drainternista.com",
      "deblax": false
    },
    {
      "origenId": "85457039",
      "nombre": "Pinedo Zagarra, Jorge Luis",
      "especialidad": "Cardiología",
      "segmento": "E",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "8809",
      "brickZona": "CHICO COLSANITAS",
      "direccion": "Calle 99 #13-90",
      "celular": "3143302318",
      "email": "pinedomed@hotmail.com",
      "deblax": false
    },
    {
      "origenId": "39684255",
      "nombre": "Ramirez Pabon, Diana",
      "especialidad": "Cardiología",
      "segmento": "E",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "8809",
      "brickZona": "CHICO COLSANITAS",
      "direccion": "Carrera 14 #96-22",
      "celular": "3005552045",
      "email": "dianarampa@yahoo.es",
      "deblax": false
    },
    {
      "origenId": "1136881270",
      "nombre": "Torres Mora, Ana María",
      "especialidad": "Medicina interna",
      "segmento": "C",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "8809",
      "brickZona": "CHICO COLSANITAS",
      "direccion": "Carrera 14 #96-22",
      "celular": "3124463552",
      "email": "anamatorres@gmail.com",
      "deblax": false
    },
    {
      "origenId": "19240009",
      "nombre": "Buitrago Gutierrez, Cristobal Tomas",
      "especialidad": "Nefrología",
      "segmento": "H,PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "8810",
      "brickZona": "CHICO",
      "direccion": "Carrera 14 #98-95",
      "celular": "3153429800",
      "email": "cristobaltomas@yahoo.com",
      "deblax": false
    },
    {
      "origenId": "52662350",
      "nombre": "Casas Montenegro, Gloria Liliana",
      "especialidad": "Medicina General",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "8815",
      "brickZona": "CHICO",
      "direccion": "Calle 100 #19A-35",
      "celular": "3138923998",
      "email": "glorialilianac@gmail.com",
      "deblax": false
    },
    {
      "origenId": "13",
      "nombre": "Monroy Ríos, Diana Judith",
      "especialidad": "Medicina General",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "8815",
      "brickZona": "CHICO",
      "direccion": "Calle 100 #19A-35",
      "celular": "3202318915",
      "email": "dianajmonroyr@gmail.com",
      "deblax": false
    },
    {
      "origenId": "7186346",
      "nombre": "Moreno Chirivi, Héctor Fabian",
      "especialidad": "Medicina interna",
      "segmento": "E",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "8815",
      "brickZona": "CHICO",
      "direccion": "Calle 100 #19A-35",
      "celular": "3108764460",
      "email": "hefamochi@hotmail.com",
      "deblax": false
    },
    {
      "origenId": "1032385370",
      "nombre": "Porras Sánchez, Daniel Fernando",
      "especialidad": "Medicina General",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "8815",
      "brickZona": "CHICO",
      "direccion": "Calle 100 #19A-35",
      "celular": "3142097519",
      "email": "danferposa@hotmail.com",
      "deblax": false
    },
    {
      "origenId": "22738501",
      "nombre": "Tulcan Rodriguez, Mónica Del Carmen",
      "especialidad": "Medicina General",
      "segmento": "H,PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "8815",
      "brickZona": "CHICO",
      "direccion": "Calle 100 #19A-35",
      "celular": "3006867530",
      "email": "mothulcan1@gmail.com",
      "deblax": false
    },
    {
      "origenId": "1020748450",
      "nombre": "Vilar Romero, Santiago Andrés",
      "especialidad": "Medicina interna",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "8815",
      "brickZona": "CHICO",
      "direccion": "Calle 100 #19A-35",
      "celular": "3044363398",
      "email": "santiagovilar@gmail.com",
      "deblax": false
    },
    {
      "origenId": "1019033975",
      "nombre": "Agreda Rudenko, Diana",
      "especialidad": "Cardiología",
      "segmento": "M",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "8818",
      "brickZona": "CHICO LOS NOGALES",
      "direccion": "Calle 95 #23-61",
      "celular": "3014313578",
      "email": "diagru@hotmail.com",
      "deblax": false
    },
    {
      "origenId": "1024602019",
      "nombre": "Bernal Sánchez, Kevin Santiago",
      "especialidad": "Medicina General",
      "segmento": "C",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "8818",
      "brickZona": "CHICO LOS NOGALES",
      "direccion": "Calle 95 #23-61",
      "celular": "3184691641",
      "email": "kbernals@unbosque.edu.co",
      "deblax": false
    },
    {
      "origenId": "1019140574",
      "nombre": "Botero Granados, Paula Juliana",
      "especialidad": "Medicina General",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "8818",
      "brickZona": "CHICO LOS NOGALES",
      "direccion": "Calle 95 #23-61",
      "celular": "3006040506",
      "email": "paula.botero2022@gmail.com",
      "deblax": false
    },
    {
      "origenId": "1020723387",
      "nombre": "Fuentes Paris, Sergio Andres",
      "especialidad": "Cardiología",
      "segmento": "M",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "8818",
      "brickZona": "CHICO LOS NOGALES",
      "direccion": "Calle 95 #23-61",
      "celular": "3003289828",
      "email": "sergiofuentesparis@gmail.com",
      "deblax": false
    },
    {
      "origenId": "52974005",
      "nombre": "González González, Diana Marisol",
      "especialidad": "Otras especialidades",
      "segmento": "E",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "8818",
      "brickZona": "CHICO LOS NOGALES",
      "direccion": "Calle 95 #23-61",
      "celular": "3103444610",
      "email": "dmagonzalez1@gmail.com",
      "deblax": false
    },
    {
      "origenId": "52395421",
      "nombre": "Roncancio Martinez, Heidy Milen",
      "especialidad": "Cardiología",
      "segmento": "E",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "8818",
      "brickZona": "CHICO LOS NOGALES",
      "direccion": "Carrera 16 #82-57",
      "celular": "3103075825",
      "email": "heidymr99@gmail.com",
      "deblax": false
    },
    {
      "origenId": "24",
      "nombre": "Alvarado Ospina, Yury Alejandra",
      "especialidad": "Endocrinología, Diabetes y Metabolismo",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "8819",
      "brickZona": "CHICO TORRE ESPECIALISTAS",
      "direccion": "Autopista Norte #100-74",
      "celular": "3132615311",
      "email": "alejitaalvarado@hotmail.com",
      "deblax": false
    },
    {
      "origenId": "1032451427",
      "nombre": "Bautista Triana, Jaime Eduardo",
      "especialidad": "Medicina interna",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "8819",
      "brickZona": "CHICO TORRE ESPECIALISTAS",
      "direccion": "Autopista Norte #100-74",
      "celular": "3185119689",
      "email": "jebautistat@gmail.com",
      "deblax": false
    },
    {
      "origenId": "53125372",
      "nombre": "Bernal Vargas, Mónica Alejandra",
      "especialidad": "Endocrinología, Diabetes y Metabolismo",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "8819",
      "brickZona": "CHICO TORRE ESPECIALISTAS",
      "direccion": "Calle 45 #30-10",
      "celular": "3005593234",
      "email": "monicabernal111@hotmail.com",
      "deblax": false
    },
    {
      "origenId": "71578881",
      "nombre": "Buitrago Torrado, Juan Carlos",
      "especialidad": "Cardiología",
      "segmento": "C",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "8819",
      "brickZona": "CHICO TORRE ESPECIALISTAS",
      "direccion": "Calle 106 #19-19",
      "celular": "3192994103",
      "email": "buitragojc@hotmail.com",
      "deblax": false
    },
    {
      "origenId": "1118535247",
      "nombre": "Camacho Bustos, Lida Andrea",
      "especialidad": "Medicina interna",
      "segmento": "E",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "8819",
      "brickZona": "CHICO TORRE ESPECIALISTAS",
      "direccion": "Autopista Norte #100-74",
      "celular": "3103164894",
      "email": "liancabu310@gmail.com",
      "deblax": false
    },
    {
      "origenId": "52331844",
      "nombre": "Contreras Fontecha, Alexandra Del Pilar",
      "especialidad": "Medicina interna",
      "segmento": "C",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "8819",
      "brickZona": "CHICO TORRE ESPECIALISTAS",
      "direccion": "Autopista Norte #100-74",
      "celular": "3203029061",
      "email": "alexadoc@hotmail.com",
      "deblax": false
    },
    {
      "origenId": "53166214",
      "nombre": "Galindo Duarte, Johanna Marcela",
      "especialidad": "Medicina General",
      "segmento": "C",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "8819",
      "brickZona": "CHICO TORRE ESPECIALISTAS",
      "direccion": "Autopista Norte #100-74",
      "celular": "",
      "email": "johannagalindo119@hotmail.com",
      "deblax": false
    },
    {
      "origenId": "51747320",
      "nombre": "Galvis Avila, Alba Luz",
      "especialidad": "Endocrinología, Diabetes y Metabolismo",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "8819",
      "brickZona": "CHICO TORRE ESPECIALISTAS",
      "direccion": "Autopista Norte #100-74",
      "celular": "3208480516",
      "email": "alugs26@yahoo.com",
      "deblax": false
    },
    {
      "origenId": "1075217814",
      "nombre": "Mejía Vidal, Liliana Esperanza",
      "especialidad": "Endocrinología, Diabetes y Metabolismo",
      "segmento": "H,PS",
      "frecuencia": 2,
      "ciudad": "BOGOTÁ",
      "brick": "8819",
      "brickZona": "CHICO TORRE ESPECIALISTAS",
      "direccion": "Carrera 23 #124-87",
      "celular": "3014231343",
      "email": "lilita_76@hotmail.com",
      "deblax": false
    },
    {
      "origenId": "1019073822",
      "nombre": "Salgado Sánchez, Juan Camilo",
      "especialidad": "Endocrinología, Diabetes y Metabolismo",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "8819",
      "brickZona": "CHICO TORRE ESPECIALISTAS",
      "direccion": "Autopista Norte #100-74",
      "celular": "3148618467",
      "email": "juansalgadoendocrino@gmail.com",
      "deblax": false
    },
    {
      "origenId": "52088510",
      "nombre": "Sanguino Lobo, Jamyr",
      "especialidad": "Endocrinología, Diabetes y Metabolismo",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "8819",
      "brickZona": "CHICO TORRE ESPECIALISTAS",
      "direccion": "Calle 97 #23-37",
      "celular": "3158532202",
      "email": "jamyrsanguinol@gmail.com",
      "deblax": false
    },
    {
      "origenId": "1053800228",
      "nombre": "Valencia Moreno, Santiago Ivan",
      "especialidad": "Medicina interna",
      "segmento": "E",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "8819",
      "brickZona": "CHICO TORRE ESPECIALISTAS",
      "direccion": "Calle 163A #13B-60",
      "celular": "",
      "email": "",
      "deblax": false
    },
    {
      "origenId": "52646230",
      "nombre": "Votto Mainieri, Yolanda Consuelo",
      "especialidad": "Medicina familiar - Medicina preventiva",
      "segmento": "E",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "8819",
      "brickZona": "CHICO TORRE ESPECIALISTAS",
      "direccion": "Avenida Carrera 58 #127-59 Loc 258 Cc Bulevar Niza",
      "celular": "3124814755",
      "email": "coquivotto@hotmail.com",
      "deblax": false
    },
    {
      "origenId": "9141783",
      "nombre": "Barrios Arias, Carlos Enrique",
      "especialidad": "Cardiología",
      "segmento": "H,PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "8824",
      "brickZona": "LA CASTELLANA",
      "direccion": "Carrera 49D #91-33",
      "celular": "3108039976",
      "email": "cbarrios114@yahoo.com",
      "deblax": false
    },
    {
      "origenId": "51995299",
      "nombre": "Bustamante Ávila, Zulma",
      "especialidad": "Medicina General",
      "segmento": "H,PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "8824",
      "brickZona": "LA CASTELLANA",
      "direccion": "Calle 47 #22-59",
      "celular": "3163362401",
      "email": "zbusavi@hotmail.com",
      "deblax": false
    },
    {
      "origenId": "1020799643",
      "nombre": "García Diaz, Laura Milena",
      "especialidad": "Otras especialidades",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "8824",
      "brickZona": "LA CASTELLANA",
      "direccion": "Calle 10 #18-75",
      "celular": "3227353860",
      "email": "lauradgarcia1394@gmail.com",
      "deblax": false
    },
    {
      "origenId": "1072645563",
      "nombre": "Lozano Hernández, Jorge Alberto",
      "especialidad": "Medicina General",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "8824",
      "brickZona": "LA CASTELLANA",
      "direccion": "Carrera 14 #94-49",
      "celular": "3166275759",
      "email": "george_lohe@hotmail.com",
      "deblax": false
    },
    {
      "origenId": "41",
      "nombre": "Peralta Zabaleta, Jose Miguel",
      "especialidad": "Medicina interna",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "8824",
      "brickZona": "LA CASTELLANA",
      "direccion": "Carrera 49D #91-33",
      "celular": "3134198045",
      "email": "jompeza@yahoo.es",
      "deblax": false
    },
    {
      "origenId": "51925594",
      "nombre": "Pilar Trujillo Laguna, Aura Del",
      "especialidad": "Cardiología",
      "segmento": "H,C",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "8824",
      "brickZona": "LA CASTELLANA",
      "direccion": "Carrera 46 #95-56",
      "celular": "3212124231",
      "email": "pilitru@hotmail.com",
      "deblax": true
    },
    {
      "origenId": "684072",
      "nombre": "Ramírez Nava, Ibsen Alberto",
      "especialidad": "Cardiología",
      "segmento": "C",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "8824",
      "brickZona": "LA CASTELLANA",
      "direccion": "Calle 95 #23-61",
      "celular": "3168220649",
      "email": "rrrana0801@gmail.com",
      "deblax": false
    },
    {
      "origenId": "80412570",
      "nombre": "Rubiano Ramirez, Lwdwing",
      "especialidad": "Cardiología",
      "segmento": "C",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "8824",
      "brickZona": "LA CASTELLANA",
      "direccion": "Carrera 46 #95-56",
      "celular": "3133872441",
      "email": "rubiano116@hotmail.com",
      "deblax": true
    },
    {
      "origenId": "80226971",
      "nombre": "Ruiz Rodríguez, Uriel Andrés",
      "especialidad": "Medicina interna",
      "segmento": "H,PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "8824",
      "brickZona": "LA CASTELLANA",
      "direccion": "Calle 8 #20-30",
      "celular": "3212214301",
      "email": "andresruizr@gmail.com",
      "deblax": false
    },
    {
      "origenId": "66995987",
      "nombre": "Suarez Manzano, Diana Patricia",
      "especialidad": "Medicina interna",
      "segmento": "H,PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "8824",
      "brickZona": "LA CASTELLANA",
      "direccion": "Carrera 14 #94-49",
      "celular": "3175109796",
      "email": "dianacart@hotmail.com",
      "deblax": false
    },
    {
      "origenId": "1013627477",
      "nombre": "Tobon Castillo, Nicolas",
      "especialidad": "Medicina General",
      "segmento": "H,PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "8824",
      "brickZona": "LA CASTELLANA",
      "direccion": "Carrera 49D #91-33",
      "celular": "3183621925",
      "email": "nicolastobonmd@gmail.com",
      "deblax": false
    },
    {
      "origenId": "77181186",
      "nombre": "Vila Uribe, Ronal David",
      "especialidad": "Medicina interna",
      "segmento": "E",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "8824",
      "brickZona": "LA CASTELLANA",
      "direccion": "Avenida Americas #57-2",
      "celular": "3232462630",
      "email": "ronalddavid29@gmail.com",
      "deblax": false
    },
    {
      "origenId": "8683102",
      "nombre": "Villanueva Munoz, Ruben Dario",
      "especialidad": "Cardiología",
      "segmento": "E",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "8824",
      "brickZona": "LA CASTELLANA",
      "direccion": "Carrera 59 #26-21",
      "celular": "3162298448",
      "email": "ruvillmu@yahoo.com.ar",
      "deblax": false
    },
    {
      "origenId": "1053604304",
      "nombre": "Alvarado Gonzalez, Luis Carlos",
      "especialidad": "Medicina familiar - Medicina preventiva",
      "segmento": "C",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "8825",
      "brickZona": "PARALELA 103",
      "direccion": "Carrera 45 #103B-03",
      "celular": "3133188330",
      "email": "docluis.alvarado@gmail.com",
      "deblax": false
    },
    {
      "origenId": "52085694",
      "nombre": "Contreras Hurtado, Claudia Milena",
      "especialidad": "Medicina interna",
      "segmento": "E",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "8825",
      "brickZona": "PARALELA 103",
      "direccion": "Autopista Norte #100-74",
      "celular": "3157820206",
      "email": "cmch75@gmail.com",
      "deblax": false
    },
    {
      "origenId": "1082995257",
      "nombre": "Fakih De Leon, Hosam",
      "especialidad": "Medicina interna",
      "segmento": "E",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "8825",
      "brickZona": "PARALELA 103",
      "direccion": "Carrera 45 #103B-03",
      "celular": "3152394553",
      "email": "hfdl9512@gmail.com",
      "deblax": false
    },
    {
      "origenId": "63480906",
      "nombre": "Florez Ortega, Nohora Stella",
      "especialidad": "Medicina interna",
      "segmento": "C",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "8825",
      "brickZona": "PARALELA 103",
      "direccion": "Calle 152 #53A-55 Tercer Piso",
      "celular": "3005713898",
      "email": "nflorezo@yahoo.es",
      "deblax": false
    },
    {
      "origenId": "1140868825",
      "nombre": "Martínez Suárez, Andrés Mauricio",
      "especialidad": "Medicina interna",
      "segmento": "C",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "8825",
      "brickZona": "PARALELA 103",
      "direccion": "Carrera 7 #40-62",
      "celular": "",
      "email": "andresmau25@hotmail.com",
      "deblax": false
    },
    {
      "origenId": "1032384706",
      "nombre": "Plazas Vargas, Francy Liliana",
      "especialidad": "Medicina interna",
      "segmento": "E",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "8825",
      "brickZona": "PARALELA 103",
      "direccion": "Carrera 45 #103B-03",
      "celular": "3175484961",
      "email": "lilianita53@hotmail.com",
      "deblax": false
    },
    {
      "origenId": "1075219783",
      "nombre": "Sandoval Riveros, Carmenza Liliana",
      "especialidad": "Medicina interna",
      "segmento": "E",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "8825",
      "brickZona": "PARALELA 103",
      "direccion": "Carrera 45 #103B-03",
      "celular": "",
      "email": "calisadi87@gmail.com",
      "deblax": false
    },
    {
      "origenId": "52530633",
      "nombre": "Vera Bernal, Leonor Milena",
      "especialidad": "Medicina familiar - Medicina preventiva",
      "segmento": "C",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "8825",
      "brickZona": "PARALELA 103",
      "direccion": "Avenida Carrera 9 #131A-02",
      "celular": "",
      "email": "leveraber@hotmail.com",
      "deblax": false
    },
    {
      "origenId": "1085903094",
      "nombre": "Quiñonez Paredes, Juan Sebastian",
      "especialidad": "Medicina Intensiva (medicina interna)",
      "segmento": "E",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "8835",
      "brickZona": "",
      "direccion": "Carrera 45 #103B-03",
      "celular": "3006755529",
      "email": "quinonez.sebas@gmail.com",
      "deblax": false
    },
    {
      "origenId": "9081541",
      "nombre": "Espinosa Espinosa, Jose Gabriel",
      "especialidad": "Cardiología",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9004",
      "brickZona": "CONTADOR",
      "direccion": "Calle 134 #13-83 Local 14",
      "celular": "3212061546",
      "email": "josegabrielm@gmail.com",
      "deblax": false
    },
    {
      "origenId": "60",
      "nombre": "Torres Navas, Adriana Gisela",
      "especialidad": "Cardiología",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9004",
      "brickZona": "CONTADOR",
      "direccion": "Avenida Carrera 9 #131A-40",
      "celular": "3193809407",
      "email": "torrnav@hotmail.com",
      "deblax": false
    },
    {
      "origenId": "61",
      "nombre": "Torres Rumie, Alfonso",
      "especialidad": "Endocrinología, Diabetes y Metabolismo",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9004",
      "brickZona": "CONTADOR",
      "direccion": "Calle 134 #7B-83 Cons 209",
      "celular": "3156855426",
      "email": "alfonsorumie57@hotmail.com",
      "deblax": false
    },
    {
      "origenId": "62",
      "nombre": "Anaya Peña, Amalia María",
      "especialidad": "Medicina interna",
      "segmento": "E",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9014",
      "brickZona": "LA CAROLINA",
      "direccion": "Carrera 14 #127-11 Cons 408",
      "celular": "3102081186",
      "email": "amaanap@hotmail.com",
      "deblax": false
    },
    {
      "origenId": "63",
      "nombre": "Arana Montoya, Indhira Patricia",
      "especialidad": "Endocrinología, Diabetes y Metabolismo",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9014",
      "brickZona": "LA CAROLINA",
      "direccion": "Avenida Calle 127 #20-16 Cons 306",
      "celular": "3007737488",
      "email": "indhiarana@hotmail.com",
      "deblax": false
    },
    {
      "origenId": "18460304",
      "nombre": "Idarraga García, Luciano",
      "especialidad": "Cardiología",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9014",
      "brickZona": "LA CAROLINA",
      "direccion": "Carrera 14 #127-11 Cons 305",
      "celular": "3102721333",
      "email": "lidarragag@hotmail.com",
      "deblax": false
    },
    {
      "origenId": "65",
      "nombre": "Ospina Arias, Jesús Fernando",
      "especialidad": "Medicina General",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9014",
      "brickZona": "LA CAROLINA",
      "direccion": "Calle 127 #20-78 Locales 206 y 207",
      "celular": "3007801701",
      "email": "fernandospina7@hotmail.com",
      "deblax": false
    },
    {
      "origenId": "52267936",
      "nombre": "Stephens Leal, Ingrid Johanna",
      "especialidad": "Endocrinología, Diabetes y Metabolismo",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9014",
      "brickZona": "LA CAROLINA",
      "direccion": "Calle 119 #7-14 Cons 304",
      "celular": "3158656464",
      "email": "stephens.ingrid@gmail.com",
      "deblax": false
    },
    {
      "origenId": "1005051390",
      "nombre": "Acevedo Montoya, Yoiner Yair",
      "especialidad": "Medicina General",
      "segmento": "C",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9018",
      "brickZona": "REINA SOFIA",
      "direccion": "Calle 23 #66-46",
      "celular": "",
      "email": "",
      "deblax": false
    },
    {
      "origenId": "79957138",
      "nombre": "Arias Barrera, Carlos Andrés",
      "especialidad": "Cardiología",
      "segmento": "H,C",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9018",
      "brickZona": "REINA SOFIA",
      "direccion": "Avenida Calle 127 #20-78",
      "celular": "3153171179",
      "email": "carlosandresmd@hotmail.com",
      "deblax": false
    },
    {
      "origenId": "79889441",
      "nombre": "Castellanos Parada, Jeffrey",
      "especialidad": "Cardiología",
      "segmento": "C",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9018",
      "brickZona": "REINA SOFIA",
      "direccion": "Calle 23 #66-46",
      "celular": "3012175026",
      "email": "jecaspar78@gmail.com",
      "deblax": false
    },
    {
      "origenId": "1020815203",
      "nombre": "Gonzalez Lopez, Angie Paola",
      "especialidad": "Medicina General",
      "segmento": "C",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9018",
      "brickZona": "REINA SOFIA",
      "direccion": "Carrera 20 #124-64",
      "celular": "3022519654",
      "email": "angiego9606@gmail.com",
      "deblax": false
    },
    {
      "origenId": "10257935",
      "nombre": "Guerrero Sandoval, Jorge Enrique",
      "especialidad": "Medicina General",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9018",
      "brickZona": "REINA SOFIA",
      "direccion": "Calle 125 #19-89 Cons 204",
      "celular": "3143217436",
      "email": "jorgeguerrero@gmail.com",
      "deblax": false
    },
    {
      "origenId": "52862231",
      "nombre": "Hernandez Buitrgo, Ursula Maryeri",
      "especialidad": "Cardiología",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9018",
      "brickZona": "REINA SOFIA",
      "direccion": "Carrera 127 #19A-44/62",
      "celular": "3103215747",
      "email": "ursulahernandez@gmail.com",
      "deblax": false
    },
    {
      "origenId": "79283543",
      "nombre": "Acevedo Peña, Juan Ramon",
      "especialidad": "Medicina interna",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9019",
      "brickZona": "REINA SOFIA",
      "direccion": "Calle 127 #20-78 Locales 206 y 207",
      "celular": "3002176225",
      "email": "jacevedo63@gmail.com",
      "deblax": false
    },
    {
      "origenId": "8666416",
      "nombre": "Acuña Olmos, Jairo",
      "especialidad": "Cardiología",
      "segmento": "E",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9019",
      "brickZona": "REINA SOFIA",
      "direccion": "Avenida Calle 127 #20-78 Cons 418",
      "celular": "3108603314",
      "email": "acuajairo@gmail.com",
      "deblax": true
    },
    {
      "origenId": "51919752",
      "nombre": "Anchique Santos, Claudia Victoria",
      "especialidad": "Cardiología",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9019",
      "brickZona": "REINA SOFIA",
      "direccion": "Calle 127 #20-78 Locales 206 y 207",
      "celular": "3157944977",
      "email": "claudia.anchiquesantos@gmail.com",
      "deblax": false
    },
    {
      "origenId": "57466523",
      "nombre": "Castillo Mejía, Milena Del Pilar",
      "especialidad": "Endocrinología, Diabetes y Metabolismo",
      "segmento": "H,PS",
      "frecuencia": 2,
      "ciudad": "BOGOTÁ",
      "brick": "9019",
      "brickZona": "REINA SOFIA",
      "direccion": "Calle 127 #19A-28 Cons 306",
      "celular": "3015684557",
      "email": "milenacastillo86@gmail.com",
      "deblax": false
    },
    {
      "origenId": "19310418",
      "nombre": "Fuentes Martínez, Gustavo",
      "especialidad": "Cardiología",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9019",
      "brickZona": "REINA SOFIA",
      "direccion": "Calle 127 #20-78 Locales 206 y 207",
      "celular": "3108680229",
      "email": "gfuentes13@hotmail.com",
      "deblax": false
    },
    {
      "origenId": "78",
      "nombre": "Giovanetti Mendoza, Hernando José",
      "especialidad": "Nefrología",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9019",
      "brickZona": "REINA SOFIA",
      "direccion": "Avenida Calle 127 #20-78 Cons 201-202-203 Y 204",
      "celular": "3102232500",
      "email": "hgiovannetti@hotmail.com",
      "deblax": false
    },
    {
      "origenId": "79",
      "nombre": "Gonzalez Barcha, Jesus",
      "especialidad": "Medicina General",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9019",
      "brickZona": "REINA SOFIA",
      "direccion": "Calle 125 #20-70 Of 204",
      "celular": "3107653724",
      "email": "jesusgonzalez62@gmail.com",
      "deblax": false
    },
    {
      "origenId": "52818072",
      "nombre": "Leal Leano, Lorena Renata",
      "especialidad": "Endocrinología, Diabetes y Metabolismo",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9019",
      "brickZona": "REINA SOFIA",
      "direccion": "Avenida Calle 127 #20-78",
      "celular": "3112511083",
      "email": "lorenaleall@hotmail.com",
      "deblax": false
    },
    {
      "origenId": "39688646",
      "nombre": "Maya Duran, Beatriz",
      "especialidad": "Cardiología",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9019",
      "brickZona": "REINA SOFIA",
      "direccion": "Avenida Calle 127 #20-78",
      "celular": "3002114856",
      "email": "bmayad@yahoo.com",
      "deblax": false
    },
    {
      "origenId": "19300865",
      "nombre": "Moscoso Martínez, Ernesto Augusto",
      "especialidad": "Endocrinología, Diabetes y Metabolismo",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9019",
      "brickZona": "REINA SOFIA",
      "direccion": "Avenida Calle 127 #21-60 Cons 421",
      "celular": "3108687713",
      "email": "drmoscoso421@hotmail.com",
      "deblax": false
    },
    {
      "origenId": "83",
      "nombre": "Oñate Donado, Rodrigo",
      "especialidad": "Cardiología",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9019",
      "brickZona": "REINA SOFIA",
      "direccion": "Avenida Calle 127 #20-78",
      "celular": "",
      "email": "",
      "deblax": false
    },
    {
      "origenId": "84",
      "nombre": "Ovalle Jaramillo, Mauricio Esteban",
      "especialidad": "Medicina interna",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9019",
      "brickZona": "REINA SOFIA",
      "direccion": "Avenida Calle 127 #20-78",
      "celular": "3104782793",
      "email": "movallej@hotmail.com",
      "deblax": false
    },
    {
      "origenId": "93409640",
      "nombre": "Patiño Pérez, Adulkarin",
      "especialidad": "Medicina interna",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9019",
      "brickZona": "REINA SOFIA",
      "direccion": "Calle 127 #20-16 Cons 305",
      "celular": "3133979200",
      "email": "adulkarin78@yahoo.es",
      "deblax": false
    },
    {
      "origenId": "19561949",
      "nombre": "Rozo Van-Strahlen, Jose Medardo",
      "especialidad": "Cardiología",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9019",
      "brickZona": "REINA SOFIA",
      "direccion": "Calle 127 Bis #19 25 Cons 311",
      "celular": "3223081314",
      "email": "yiaji8@hotmail.com",
      "deblax": false
    },
    {
      "origenId": "87",
      "nombre": "Alvarado Echeona, Katerin",
      "especialidad": "Medicina familiar - Medicina preventiva",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9020",
      "brickZona": "BULEVAR NIZA",
      "direccion": "Avenida Carrera 58 #127-59 Local 282 Piso 2 CC Bulevar Niza",
      "celular": "3125412031",
      "email": "kate1980_12@hotmail.com",
      "deblax": false
    },
    {
      "origenId": "88",
      "nombre": "Armenta Polo, Ruth Yuranys",
      "especialidad": "Medicina familiar - Medicina preventiva",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9020",
      "brickZona": "BULEVAR NIZA",
      "direccion": "Avenida Carrera 58 #127-59 Local 282 Piso 2 CC Bulevar Niza",
      "celular": "3116534994",
      "email": "ruthyap@hotmail.com",
      "deblax": false
    },
    {
      "origenId": "89",
      "nombre": "Babilonia Luna, Gustavo Adolfo",
      "especialidad": "Cardiología",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9020",
      "brickZona": "BULEVAR NIZA",
      "direccion": "Avenida Carrera 58 #127-59 Local 282 Piso 2 CC Bulevar Niza",
      "celular": "",
      "email": "",
      "deblax": false
    },
    {
      "origenId": "90",
      "nombre": "Guerrero Quintero, Yully Andrea",
      "especialidad": "Medicina interna",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9020",
      "brickZona": "BULEVAR NIZA",
      "direccion": "Avenida Carrera 58 #127-59 Local 282 Piso 2 CC Bulevar Niza",
      "celular": "3214536776",
      "email": "yguerrero@cronicos.com",
      "deblax": false
    },
    {
      "origenId": "91",
      "nombre": "Heleno Jaramillo, Andrea Del Pilar",
      "especialidad": "Medicina interna",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9020",
      "brickZona": "BULEVAR NIZA",
      "direccion": "Avenida Carrera 58 #127-59 Local 282 Piso 2 CC Bulevar Niza",
      "celular": "3223663982",
      "email": "helenoand@gmail.com",
      "deblax": false
    },
    {
      "origenId": "92",
      "nombre": "Vargas Donoso, Margarita Maria",
      "especialidad": "Medicina General",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9020",
      "brickZona": "BULEVAR NIZA",
      "direccion": "Avenida Carrera 58 #127-59 Local 282 Piso 2 CC Bulevar Niza",
      "celular": "3165243611",
      "email": "margaritavd@gmail.com",
      "deblax": false
    },
    {
      "origenId": "52418265",
      "nombre": "Figueredo Figueredo, Claudia Rocio",
      "especialidad": "Medicina familiar - Medicina preventiva",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9025",
      "brickZona": "CEDRITOS-COLINA",
      "direccion": "Calle 151 #54-45",
      "celular": "3004919136",
      "email": "claufigue94@gmail.com",
      "deblax": false
    },
    {
      "origenId": "52211198",
      "nombre": "Guerrero Legro, Margott Alida",
      "especialidad": "Medicina interna",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9026",
      "brickZona": "COLSANITAS CEDROBOLIVAR",
      "direccion": "Carrera 14 #96-22",
      "celular": "",
      "email": "margott.guerrero@gmail.com",
      "deblax": false
    },
    {
      "origenId": "1049612925",
      "nombre": "Hurtado Amezquita, Yesid Camilo",
      "especialidad": "Endocrinología, Diabetes y Metabolismo",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9026",
      "brickZona": "COLSANITAS CEDROBOLIVAR",
      "direccion": "Calle 152 #19-04",
      "celular": "3142384712",
      "email": "camilohurtado88@gmail.com",
      "deblax": false
    },
    {
      "origenId": "1098704113",
      "nombre": "Mejia Sandoval, Harvey Julian",
      "especialidad": "Endocrinología, Diabetes y Metabolismo",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9026",
      "brickZona": "COLSANITAS CEDROBOLIVAR",
      "direccion": "Calle 152 #19-44",
      "celular": "3124836558",
      "email": "harveyjmesan@gmail.com",
      "deblax": false
    },
    {
      "origenId": "80135242",
      "nombre": "Prieto Robayo, Gustavo Iván",
      "especialidad": "Cardiología",
      "segmento": "H,PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9026",
      "brickZona": "COLSANITAS CEDROBOLIVAR",
      "direccion": "Carrera 45 #94-71",
      "celular": "",
      "email": "akash.prieto@gmail.com",
      "deblax": false
    },
    {
      "origenId": "98",
      "nombre": "Rozo Maragua, Diana Fernanda",
      "especialidad": "Endocrinología, Diabetes y Metabolismo",
      "segmento": "PS",
      "frecuencia": 2,
      "ciudad": "BOGOTÁ",
      "brick": "9026",
      "brickZona": "COLSANITAS CEDROBOLIVAR",
      "direccion": "Calle 151 #54-45",
      "celular": "3202749663",
      "email": "drozomaragua@gmail.com",
      "deblax": false
    },
    {
      "origenId": "50926505",
      "nombre": "Villeros Navarro, Angela Paola",
      "especialidad": "Medicina familiar - Medicina preventiva",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9026",
      "brickZona": "COLSANITAS CEDROBOLIVAR",
      "direccion": "Calle 151 #54-15",
      "celular": "3108038915",
      "email": "avillerosn@hotmail.com",
      "deblax": false
    },
    {
      "origenId": "80223799",
      "nombre": "Barrera Garavito, Edgar Camilo",
      "especialidad": "Medicina interna",
      "segmento": "E",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9027",
      "brickZona": "LA CARDIO",
      "direccion": "Calle 163A #13B-60",
      "celular": "3174397361",
      "email": "",
      "deblax": false
    },
    {
      "origenId": "7176861",
      "nombre": "Bustos Martinez, Jorge Arturo",
      "especialidad": "Cardiología",
      "segmento": "H,C",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9027",
      "brickZona": "LA CARDIO",
      "direccion": "Calle 163A #13B-60",
      "celular": "3102067577",
      "email": "jbustosm@cardioinfantil.org",
      "deblax": false
    },
    {
      "origenId": "1030631195",
      "nombre": "Cabra Narváez, Angie Paola",
      "especialidad": "Otras especialidades",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9027",
      "brickZona": "LA CARDIO",
      "direccion": "Calle 163A #13B-60",
      "celular": "",
      "email": "",
      "deblax": false
    },
    {
      "origenId": "1129578142",
      "nombre": "Campo Bautista, Esther María",
      "especialidad": "Cardiología",
      "segmento": "C",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9027",
      "brickZona": "LA CARDIO",
      "direccion": "Calle 163A #13B-60",
      "celular": "3156123323",
      "email": "esthercampob@hotmail.com",
      "deblax": false
    },
    {
      "origenId": "1020789089",
      "nombre": "Cruz Cuevas, José David",
      "especialidad": "Medicina interna",
      "segmento": "M",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9027",
      "brickZona": "LA CARDIO",
      "direccion": "Calle 163A #13B-60",
      "celular": "3133480516",
      "email": "jdavid940116@gmail.com",
      "deblax": false
    },
    {
      "origenId": "77028381",
      "nombre": "Del Castillo Lezaca, Javier Fernando",
      "especialidad": "Cardiología",
      "segmento": "M",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9027",
      "brickZona": "LA CARDIO",
      "direccion": "Carrera 13 #49-40",
      "celular": "3173141349",
      "email": "javierdelcastillome@hotmail.com",
      "deblax": false
    },
    {
      "origenId": "52692754",
      "nombre": "Dueñas Criado, Karen Alexandra",
      "especialidad": "Cardiología",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9027",
      "brickZona": "LA CARDIO",
      "direccion": "Calle 163A #13B-60",
      "celular": "3007022904",
      "email": "kcduenas7@gmail.com",
      "deblax": false
    },
    {
      "origenId": "79146487",
      "nombre": "Franco Reyes, Camilo",
      "especialidad": "Cardiología",
      "segmento": "E",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9027",
      "brickZona": "LA CARDIO",
      "direccion": "Calle 163A #13B-60",
      "celular": "3102106899",
      "email": "kduenasmed@hotmail.com",
      "deblax": false
    },
    {
      "origenId": "1020780139",
      "nombre": "Holguin Riaño, Diego Fabian",
      "especialidad": "Medicina interna",
      "segmento": "C",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9027",
      "brickZona": "LA CARDIO",
      "direccion": "Avenida Carrera 9 #131A-40",
      "celular": "3114485698",
      "email": "diegoholguinmd@hotmail.com",
      "deblax": false
    },
    {
      "origenId": "79148936",
      "nombre": "Isaza Restrepo, Daniel",
      "especialidad": "Medicina Intensiva (medicina interna)",
      "segmento": "H,C",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9027",
      "brickZona": "LA CARDIO",
      "direccion": "Carrera 13B #161-85",
      "celular": "3102982888",
      "email": "disaza@cardioinfantil.com.co",
      "deblax": true
    },
    {
      "origenId": "88250789",
      "nombre": "Landazabal Balaguera, Jorge Alexander",
      "especialidad": "Cardiología",
      "segmento": "E",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9027",
      "brickZona": "LA CARDIO",
      "direccion": "Calle 163A #13B-60",
      "celular": "3124353598",
      "email": "jlandazabal@lacardio.org",
      "deblax": false
    },
    {
      "origenId": "83233124",
      "nombre": "Lizcano Losada, Fernando",
      "especialidad": "Endocrinología, Diabetes y Metabolismo",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9027",
      "brickZona": "LA CARDIO",
      "direccion": "Calle 163A #13B-60",
      "celular": "3144120052",
      "email": "fernandolizcano@hotmail.com",
      "deblax": false
    },
    {
      "origenId": "10297559",
      "nombre": "Luna Vela, Fredy Andres",
      "especialidad": "Endocrinología, Diabetes y Metabolismo",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9027",
      "brickZona": "LA CARDIO",
      "direccion": "Calle 163A #13B-60",
      "celular": "3002705448",
      "email": "fredylunaendocrino@hotmail.com",
      "deblax": false
    },
    {
      "origenId": "79296249",
      "nombre": "Marín Arbeláez, Fernando",
      "especialidad": "Cardiología",
      "segmento": "E",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9027",
      "brickZona": "LA CARDIO",
      "direccion": "Calle 163A #13B-60",
      "celular": "3143310732",
      "email": "fmarin@cardioinfantil.org",
      "deblax": true
    },
    {
      "origenId": "19258605",
      "nombre": "Martínez Rincón, Jorge Eliecer",
      "especialidad": "Cardiología",
      "segmento": "H,C",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9027",
      "brickZona": "LA CARDIO",
      "direccion": "Calle 163A #13B-60",
      "celular": "3164672905",
      "email": "je_martinezr@yahoo.com",
      "deblax": false
    },
    {
      "origenId": "1018425962",
      "nombre": "Medina Mur, Ramon Ivan",
      "especialidad": "Cardiología",
      "segmento": "E",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9027",
      "brickZona": "LA CARDIO",
      "direccion": "Transversal 3 #49-00",
      "celular": "",
      "email": "ramon8809@hotmail.com",
      "deblax": true
    },
    {
      "origenId": "52530906",
      "nombre": "Molano Triviño, Alejandra Patricia",
      "especialidad": "Nefrología",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9027",
      "brickZona": "LA CARDIO",
      "direccion": "Calle 163A #13B-60",
      "celular": "3153449865",
      "email": "alepatrimoltri@gmail.com",
      "deblax": false
    },
    {
      "origenId": "1110467616",
      "nombre": "Moreno León, Julian Mauricio",
      "especialidad": "Medicina interna",
      "segmento": "C",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9027",
      "brickZona": "LA CARDIO",
      "direccion": "Carrera 163B #13B-60",
      "celular": "",
      "email": "",
      "deblax": false
    },
    {
      "origenId": "79803164",
      "nombre": "Novoa Ramirez, Danny Julian",
      "especialidad": "Medicina interna",
      "segmento": "E",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9027",
      "brickZona": "LA CARDIO",
      "direccion": "Calle 163A #13B-60",
      "celular": "3114813482",
      "email": "",
      "deblax": false
    },
    {
      "origenId": "93410411",
      "nombre": "Omeara Novoa, Miguel Augusto",
      "especialidad": "Endocrinología, Diabetes y Metabolismo",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9027",
      "brickZona": "LA CARDIO",
      "direccion": "Calle 163A #13B-60",
      "celular": "3182725831",
      "email": "miguelomeara27@yahoo.com",
      "deblax": false
    },
    {
      "origenId": "83237797",
      "nombre": "Ortiz Trujillo, Carlos Andres",
      "especialidad": "Cardiología",
      "segmento": "C",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9027",
      "brickZona": "LA CARDIO",
      "direccion": "Calle 163A #13B-60",
      "celular": "3142970988",
      "email": "cortiz123@gmail.com",
      "deblax": true
    },
    {
      "origenId": "7185708",
      "nombre": "Perez Fernandez, Oscar Mauricio",
      "especialidad": "Cardiología",
      "segmento": "H,E",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9027",
      "brickZona": "LA CARDIO",
      "direccion": "Calle 163A #13B-60",
      "celular": "3154467878",
      "email": "operezmedic23@gmail.com",
      "deblax": false
    },
    {
      "origenId": "79996080",
      "nombre": "Ramírez Martínez, John Alexander",
      "especialidad": "Cardiología",
      "segmento": "M",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9027",
      "brickZona": "LA CARDIO",
      "direccion": "Calle 163A #13B-60",
      "celular": "3212099212",
      "email": "johnalexander.ramirez@gmail.com",
      "deblax": true
    },
    {
      "origenId": "63500278",
      "nombre": "Rodriguez Gonzalez, Maria Juliana",
      "especialidad": "Cardiología",
      "segmento": "M",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9027",
      "brickZona": "LA CARDIO",
      "direccion": "Calle 163A #13B-60",
      "celular": "3164821052",
      "email": "juli752000@yahoo.com",
      "deblax": false
    },
    {
      "origenId": "12116223",
      "nombre": "Valenzuela Rincon, Alex",
      "especialidad": "Endocrinología, Diabetes y Metabolismo",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9027",
      "brickZona": "LA CARDIO",
      "direccion": "Calle 163A #13B-60",
      "celular": "3002670608",
      "email": "avalenzuela@cardioinfantil.org",
      "deblax": false
    },
    {
      "origenId": "80093293",
      "nombre": "Zuñiga Rodriguez, Eduardo Adolfo",
      "especialidad": "Nefrología",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9027",
      "brickZona": "LA CARDIO",
      "direccion": "Calle 163A #13B-60",
      "celular": "3212032367",
      "email": "zuniga81@gmail.com",
      "deblax": false
    },
    {
      "origenId": "126",
      "nombre": "López Pérez, Samuel Guillermo",
      "especialidad": "Medicina interna",
      "segmento": "E",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9104",
      "brickZona": "LA COLINA",
      "direccion": "Calle 164 #7F-10",
      "celular": "",
      "email": "",
      "deblax": false
    },
    {
      "origenId": "127",
      "nombre": "Ortiz Alvarez, Ivan Dario",
      "especialidad": "Endocrinología, Diabetes y Metabolismo",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9104",
      "brickZona": "LA COLINA",
      "direccion": "Carrera 59 #152-19",
      "celular": "3167474207",
      "email": "ivandmed@yahoo.com",
      "deblax": false
    },
    {
      "origenId": "79299271",
      "nombre": "Agatón Santander, Darío Antonio",
      "especialidad": "Medicina familiar - Medicina preventiva",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9118",
      "brickZona": "",
      "direccion": "Carrera 111 #159A-61",
      "celular": "3178958742",
      "email": "dario.agaton@juanncorpas.edu.co",
      "deblax": false
    },
    {
      "origenId": "129",
      "nombre": "Maldonado Acosta, Luis Miguel",
      "especialidad": "Endocrinología, Diabetes y Metabolismo",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "BOGOTÁ",
      "brick": "9104",
      "brickZona": "LA COLINA",
      "direccion": "Diagonal 152 #36-44",
      "celular": "3203405283",
      "email": "lmaldonadoacosta@gmail.com",
      "deblax": false
    },
    {
      "origenId": "93367369",
      "nombre": "Hernandez Gaviria, Carlos Augusto",
      "especialidad": "Medicina General",
      "segmento": "H,PS",
      "frecuencia": 1,
      "ciudad": "IBAGUÉ",
      "brick": "5138",
      "brickZona": "IBAGUE",
      "direccion": "Calle 11 Sur #10-56",
      "celular": "3123783808",
      "email": "carlosahernandezg@hotmail.com",
      "deblax": false
    },
    {
      "origenId": "81754045",
      "nombre": "Bohorquez Cubillos, Hernan David",
      "especialidad": "Cardiología",
      "segmento": "M",
      "frecuencia": 1,
      "ciudad": "IBAGUÉ",
      "brick": "5217",
      "brickZona": "IBAGUE",
      "direccion": "Calle 33 #4A-50",
      "celular": "3212003655",
      "email": "",
      "deblax": true
    },
    {
      "origenId": "132",
      "nombre": "Chamat Garcia, Oscar Gustavo",
      "especialidad": "Medicina General",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "IBAGUÉ",
      "brick": "5217",
      "brickZona": "IBAGUE",
      "direccion": "Calle 31 #4D-8",
      "celular": "3157804184",
      "email": "oscarchamat@yahoo.com",
      "deblax": false
    },
    {
      "origenId": "60381170",
      "nombre": "Chaparro Quintero, Zully Adriana",
      "especialidad": "Medicina interna",
      "segmento": "E",
      "frecuencia": 1,
      "ciudad": "IBAGUÉ",
      "brick": "5217",
      "brickZona": "IBAGUE",
      "direccion": "Calle 33 #4A-50",
      "celular": "3112310759",
      "email": "zullya30@hotmail.com",
      "deblax": false
    },
    {
      "origenId": "1018436848",
      "nombre": "Cifuentes Tarquino, Jennifer",
      "especialidad": "Cardiología",
      "segmento": "E",
      "frecuencia": 1,
      "ciudad": "IBAGUÉ",
      "brick": "5217",
      "brickZona": "IBAGUE",
      "direccion": "Carrera 5 #31-114",
      "celular": "3004624431",
      "email": "jen_cifuentes@hotmail.com",
      "deblax": true
    },
    {
      "origenId": "1024461251",
      "nombre": "Monroy Pinilla, Maria Angelica",
      "especialidad": "Medicina interna",
      "segmento": "E",
      "frecuencia": 1,
      "ciudad": "IBAGUÉ",
      "brick": "5217",
      "brickZona": "IBAGUE",
      "direccion": "Calle 41 #5-40",
      "celular": "",
      "email": "aneida7@hotmail.com",
      "deblax": false
    },
    {
      "origenId": "65783946",
      "nombre": "Morales Viña, Andrea Del Pilar",
      "especialidad": "Medicina familiar - Medicina preventiva",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "IBAGUÉ",
      "brick": "5217",
      "brickZona": "IBAGUE",
      "direccion": "Calle 19 #7-87",
      "celular": "3112762794",
      "email": "mdandrepilimorales@hotmail.com",
      "deblax": false
    },
    {
      "origenId": "5957167",
      "nombre": "Cuartas Ochoa, Alfonso",
      "especialidad": "Medicina General",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "IBAGUÉ",
      "brick": "5218",
      "brickZona": "IBAGUE",
      "direccion": "Calle 33 #4A-50",
      "celular": "3153972845",
      "email": "alfonsocuartasochoa@hotmail.com",
      "deblax": false
    },
    {
      "origenId": "9725621",
      "nombre": "Gil Aldana, Victor José",
      "especialidad": "Cardiología",
      "segmento": "E",
      "frecuencia": 1,
      "ciudad": "IBAGUÉ",
      "brick": "5218",
      "brickZona": "IBAGUE",
      "direccion": "Calle 59A #5A - 00 Sur",
      "celular": "3133862552",
      "email": "victorgaldana@gmail.com",
      "deblax": false
    },
    {
      "origenId": "93389770",
      "nombre": "Giraldo Mejia, Carlos Eduardo",
      "especialidad": "Medicina General",
      "segmento": "E",
      "frecuencia": 1,
      "ciudad": "IBAGUÉ",
      "brick": "5218",
      "brickZona": "IBAGUE",
      "direccion": "Avenida Guavinal #69-02",
      "celular": "3155878878",
      "email": "edugiraldo1973@hotmail.com",
      "deblax": false
    },
    {
      "origenId": "51892220",
      "nombre": "Guevara Sanabria, Yolanda Ines",
      "especialidad": "Nefrología",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "IBAGUÉ",
      "brick": "5218",
      "brickZona": "IBAGUE",
      "direccion": "Carrera 12 Sur #93-21 Medicadiz Cons 207",
      "celular": "3124544662",
      "email": "yguevaras@yahoo.com",
      "deblax": false
    },
    {
      "origenId": "72072579",
      "nombre": "Morales Rodriguez, Jesus Maria",
      "especialidad": "Nefrología",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "IBAGUÉ",
      "brick": "5218",
      "brickZona": "IBAGUE",
      "direccion": "Carrera 5 #30-43",
      "celular": "3126211276",
      "email": "moralitomdjm@hotmail.com",
      "deblax": false
    },
    {
      "origenId": "142",
      "nombre": "Nieto Montenegro, Felix Orlando",
      "especialidad": "Medicina General",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "IBAGUÉ",
      "brick": "5218",
      "brickZona": "IBAGUE",
      "direccion": "Calle 33 #4A-50",
      "celular": "3152577478",
      "email": "felixnimo@hotmail.com",
      "deblax": false
    },
    {
      "origenId": "143",
      "nombre": "Norato Montoya, Johana Marcela",
      "especialidad": "Medicina General",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "IBAGUÉ",
      "brick": "5218",
      "brickZona": "IBAGUE",
      "direccion": "Carrera 5 #30-43",
      "celular": "",
      "email": "",
      "deblax": false
    },
    {
      "origenId": "93359219",
      "nombre": "Oviedo Leonel, Antonio Jose",
      "especialidad": "Medicina interna",
      "segmento": "H,PS",
      "frecuencia": 1,
      "ciudad": "IBAGUÉ",
      "brick": "5218",
      "brickZona": "IBAGUE",
      "direccion": "Carrera 6A #60-19",
      "celular": "3102823544",
      "email": "antoniojoseoviedo3@hotmail.com",
      "deblax": false
    },
    {
      "origenId": "80549167",
      "nombre": "Parra Jimenez, Juan David",
      "especialidad": "Cardiología",
      "segmento": "P",
      "frecuencia": 1,
      "ciudad": "IBAGUÉ",
      "brick": "5218",
      "brickZona": "IBAGUE",
      "direccion": "Carrera 10 Sur #66A-70",
      "celular": "3214443464",
      "email": "judaparra84@hotmail.com",
      "deblax": false
    },
    {
      "origenId": "72293355",
      "nombre": "Polifrony Avendaño, Luigi Enrique",
      "especialidad": "Cardiología",
      "segmento": "C",
      "frecuencia": 1,
      "ciudad": "IBAGUÉ",
      "brick": "5218",
      "brickZona": "IBAGUE",
      "direccion": "Carrera 4F #34-229",
      "celular": "3022595013",
      "email": "luigipolia@yahoo.es",
      "deblax": false
    },
    {
      "origenId": "147",
      "nombre": "Rodriguez Vivas, Maria Carolina",
      "especialidad": "Medicina interna",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "IBAGUÉ",
      "brick": "5218",
      "brickZona": "IBAGUE",
      "direccion": "Calle 32 #4 C-40",
      "celular": "3002084548",
      "email": "caro.edu.md@gmail.com",
      "deblax": false
    },
    {
      "origenId": "148",
      "nombre": "Ruiz Schnitter, Juan Antonio",
      "especialidad": "Cardiología",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "IBAGUÉ",
      "brick": "5218",
      "brickZona": "IBAGUE",
      "direccion": "Calle 43 #4-26 Cons 406",
      "celular": "3014775954",
      "email": "jruizcsh@gmail.com",
      "deblax": false
    },
    {
      "origenId": "14219080",
      "nombre": "Toro Paramo, Jose Alejandro",
      "especialidad": "Medicina interna",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "IBAGUÉ",
      "brick": "5218",
      "brickZona": "IBAGUE",
      "direccion": "Calle 43 #4-26",
      "celular": "3138897716",
      "email": "torojosealejandro@yahoo.com",
      "deblax": false
    },
    {
      "origenId": "93411804",
      "nombre": "Torres Garcia, Edwin Alberto",
      "especialidad": "Medicina interna",
      "segmento": "C",
      "frecuencia": 1,
      "ciudad": "IBAGUÉ",
      "brick": "5218",
      "brickZona": "IBAGUE",
      "direccion": "Calle 33 #4A-50",
      "celular": "3184561990",
      "email": "medicoeatg3237@hotmail.com",
      "deblax": false
    },
    {
      "origenId": "1110462846",
      "nombre": "Vela Quevedo, Lizeth",
      "especialidad": "Medicina General",
      "segmento": "E",
      "frecuencia": 1,
      "ciudad": "IBAGUÉ",
      "brick": "5218",
      "brickZona": "IBAGUE",
      "direccion": "Calle 41 #5-40",
      "celular": "3124356788",
      "email": "liza60@hotmail.com",
      "deblax": false
    },
    {
      "origenId": "77163148",
      "nombre": "Álvarez Tejedor, José Joaquín",
      "especialidad": "Medicina interna",
      "segmento": "C",
      "frecuencia": 1,
      "ciudad": "IBAGUÉ",
      "brick": "5219",
      "brickZona": "IBAGUE",
      "direccion": "Transversal 1 Sur #44-229",
      "celular": "3106737160",
      "email": "dr.josejalvareztejedor@gmail.com",
      "deblax": false
    },
    {
      "origenId": "93401278",
      "nombre": "Caro Zambrano, Carlos Ariel",
      "especialidad": "Endocrinología, Diabetes y Metabolismo",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "IBAGUÉ",
      "brick": "5219",
      "brickZona": "IBAGUE",
      "direccion": "Carrera 12 Sur #93-21 Vía Aeropuerto Perales Torre De Especialistas Cons 806",
      "celular": "3188044476",
      "email": "carloscaroendocrinologo@hotmail.com",
      "deblax": false
    },
    {
      "origenId": "19138785",
      "nombre": "Cepeda Garzón, Carlos Eduardo",
      "especialidad": "Cardiología",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "IBAGUÉ",
      "brick": "5219",
      "brickZona": "IBAGUE",
      "direccion": "Carrera 12S #93 - 134",
      "celular": "3212090828",
      "email": "cardiodx@gmail.com",
      "deblax": true
    },
    {
      "origenId": "14396210",
      "nombre": "Ducuara Tovar, Carlos Hernán",
      "especialidad": "Cardiología",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "IBAGUÉ",
      "brick": "5219",
      "brickZona": "IBAGUE",
      "direccion": "Carrera 2 Este #67B-90",
      "celular": "",
      "email": "drcarlosducuara@gmaii.com",
      "deblax": false
    },
    {
      "origenId": "93379131",
      "nombre": "Jiménez Medina, Germán Alonso",
      "especialidad": "Medicina interna",
      "segmento": "H,E",
      "frecuencia": 1,
      "ciudad": "IBAGUÉ",
      "brick": "5219",
      "brickZona": "IBAGUE",
      "direccion": "Carrera 12S #93-21",
      "celular": "3155311196",
      "email": "jimenez.70@gmail.com",
      "deblax": false
    },
    {
      "origenId": "38144920",
      "nombre": "Lizcano Chacon, Melissa Lynette",
      "especialidad": "Medicina General",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "IBAGUÉ",
      "brick": "5219",
      "brickZona": "IBAGUE",
      "direccion": "Avenida Guabinal #69-02",
      "celular": "3133250529",
      "email": "lizcanomd80@gmail.com",
      "deblax": false
    },
    {
      "origenId": "80008418",
      "nombre": "Martinez Muñoz, Andres Fernando",
      "especialidad": "Medicina General",
      "segmento": "H,PS",
      "frecuencia": 1,
      "ciudad": "IBAGUÉ",
      "brick": "5219",
      "brickZona": "IBAGUE",
      "direccion": "Avenida Ferrocarril #4A-00",
      "celular": "3014311825",
      "email": "doctorandres@hotmail.com",
      "deblax": false
    },
    {
      "origenId": "75074480",
      "nombre": "Osorio Galindo, Rodolfo",
      "especialidad": "Medicina familiar - Medicina preventiva",
      "segmento": "C",
      "frecuencia": 1,
      "ciudad": "IBAGUÉ",
      "brick": "5219",
      "brickZona": "IBAGUE",
      "direccion": "Calle 19 #7-75",
      "celular": "3012911780",
      "email": "rodolfoosg@hotmail.com",
      "deblax": false
    },
    {
      "origenId": "28538724",
      "nombre": "Palma Ramirez, Sandra Rocio",
      "especialidad": "Medicina familiar - Medicina preventiva",
      "segmento": "E",
      "frecuencia": 1,
      "ciudad": "IBAGUÉ",
      "brick": "5219",
      "brickZona": "IBAGUE",
      "direccion": "Calle 60 #6-38",
      "celular": "3115067385",
      "email": "san.palma01@hotmail.com",
      "deblax": false
    },
    {
      "origenId": "93379295",
      "nombre": "Rivera Angel, Javier Mauricio",
      "especialidad": "Medicina General",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "IBAGUÉ",
      "brick": "5219",
      "brickZona": "IBAGUE",
      "direccion": "Carrera 5 #30B-15",
      "celular": "3134334213",
      "email": "mauroangel@gmail.com",
      "deblax": false
    },
    {
      "origenId": "14227461",
      "nombre": "Suarez Robledo, Pedro Nel",
      "especialidad": "Medicina General",
      "segmento": "H,PS",
      "frecuencia": 1,
      "ciudad": "IBAGUÉ",
      "brick": "5219",
      "brickZona": "IBAGUE",
      "direccion": "Carrera 5A #36-21",
      "celular": "3103634503",
      "email": "pedros67@hotmail.com",
      "deblax": false
    },
    {
      "origenId": "65634277",
      "nombre": "Umaña Bastidas, Maritza",
      "especialidad": "Medicina familiar - Medicina preventiva",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "IBAGUÉ",
      "brick": "5219",
      "brickZona": "IBAGUE",
      "direccion": "Transversal 1 Sur #44-229",
      "celular": "",
      "email": "tatu0107@hotmail.com",
      "deblax": false
    },
    {
      "origenId": "2000016206",
      "nombre": "Zambrano González, María Laura",
      "especialidad": "Medicina interna",
      "segmento": "E",
      "frecuencia": 1,
      "ciudad": "IBAGUÉ",
      "brick": "5219",
      "brickZona": "IBAGUE",
      "direccion": "Transversal 1 Sur #44-229",
      "celular": "3005485369",
      "email": "marialaurazambrano1985@gmail.com",
      "deblax": false
    },
    {
      "origenId": "18495666",
      "nombre": "Zarate Rodriguez, Juan Carlos",
      "especialidad": "Medicina interna",
      "segmento": "H,E",
      "frecuencia": 1,
      "ciudad": "IBAGUÉ",
      "brick": "5219",
      "brickZona": "IBAGUE",
      "direccion": "Carrera 12 Sur #93-134 Cons 911 y 912",
      "celular": "3165258789",
      "email": "juanczarate19@hotmail.com",
      "deblax": false
    },
    {
      "origenId": "93370504",
      "nombre": "Ascensio Duran, Nestor Fernando",
      "especialidad": "Cardiología",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "IBAGUÉ",
      "brick": "5220",
      "brickZona": "IBAGUE",
      "direccion": "Carrera 1 #12-22",
      "celular": "3183100632",
      "email": "nfascencio@yahoo.com",
      "deblax": true
    },
    {
      "origenId": "167",
      "nombre": "Caypa Rodriguez, Juan Antonio",
      "especialidad": "Medicina General",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "IBAGUÉ",
      "brick": "5220",
      "brickZona": "IBAGUE",
      "direccion": "Carrera 5 #63 88",
      "celular": "3152747523",
      "email": "juancaypa@hotmail.com",
      "deblax": false
    },
    {
      "origenId": "14399696",
      "nombre": "Chavarro Herrera, Luis Alfonso",
      "especialidad": "Medicina General",
      "segmento": "M",
      "frecuencia": 1,
      "ciudad": "IBAGUÉ",
      "brick": "5220",
      "brickZona": "IBAGUE",
      "direccion": "Carrera 1 #12-22",
      "celular": "3002667078",
      "email": "alfo884@hotmail.com",
      "deblax": false
    },
    {
      "origenId": "10098279",
      "nombre": "Osorio Salazar, Carlos Javier",
      "especialidad": "Endocrinología, Diabetes y Metabolismo",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "IBAGUÉ",
      "brick": "5220",
      "brickZona": "IBAGUE",
      "direccion": "Calle 33 #4A-50",
      "celular": "3158005381",
      "email": "cajaoso12@hotmail.com",
      "deblax": false
    },
    {
      "origenId": "10528046",
      "nombre": "Quintero Calderón, Rubén",
      "especialidad": "Medicina General",
      "segmento": "H,PS",
      "frecuencia": 1,
      "ciudad": "IBAGUÉ",
      "brick": "5220",
      "brickZona": "IBAGUE",
      "direccion": "Carrera 5 #63-14 Jordán Etapa 2",
      "celular": "3002812818",
      "email": "ruquic3@gmail.com",
      "deblax": false
    },
    {
      "origenId": "171",
      "nombre": "Bonilla Garzon, Marco Antonio",
      "especialidad": "Medicina General",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "IBAGUÉ",
      "brick": "5221",
      "brickZona": "IBAGUE",
      "direccion": "Calle 8 #7-75",
      "celular": "3125828906",
      "email": "marcobonillamd@gmail.com",
      "deblax": false
    },
    {
      "origenId": "172",
      "nombre": "Rodriguez Acosta, Hernan",
      "especialidad": "Medicina General",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "IBAGUÉ",
      "brick": "5221",
      "brickZona": "IBAGUE",
      "direccion": "Calle 15 #05-35",
      "celular": "3112763221",
      "email": "hrodrigueza58@hotmail.com",
      "deblax": false
    },
    {
      "origenId": "1234641581",
      "nombre": "Santos Savala, Alejandro Miguel",
      "especialidad": "Cardiología",
      "segmento": "C",
      "frecuencia": 1,
      "ciudad": "IBAGUÉ",
      "brick": "5224",
      "brickZona": "",
      "direccion": "Avenida 19 y Carrera 13 Vía Calambeo",
      "celular": "3165709731",
      "email": "dralejandrosantos@gmail.com",
      "deblax": true
    },
    {
      "origenId": "665429",
      "nombre": "Bastardo Lopez, Alexis Jose",
      "especialidad": "Cardiología",
      "segmento": "M",
      "frecuencia": 1,
      "ciudad": "IBAGUÉ",
      "brick": "7557",
      "brickZona": "",
      "direccion": "Avenida 19 y Carrera 13 Vía Calambeo",
      "celular": "3102596092",
      "email": "alexcardmd@hotmail.com",
      "deblax": true
    },
    {
      "origenId": "1019070740",
      "nombre": "Beltrán Martínez, Diego Alfonso",
      "especialidad": "Medicina familiar - Medicina preventiva",
      "segmento": "PS",
      "frecuencia": 1,
      "ciudad": "IBAGUÉ",
      "brick": "8825",
      "brickZona": "PARALELA 103",
      "direccion": "Carrera 12 Sur #93-21",
      "celular": "3058996838",
      "email": "centro@socmef.org",
      "deblax": false
    }
  ],
  "farmacias": [
    {
      "origenId": "0015f00000X9P6rAAF",
      "nombre": "Droguería Alemana 106",
      "cadena": "",
      "ciudad": "IBAGUÉ",
      "brick": "5219",
      "brickZona": "IBAGUE",
      "direccion": "Carrera 16 Sur #96-48 Local 6 Centro Comercial Mercacentro 10 Poblado",
      "frecuencia": 1,
      "adium": false
    },
    {
      "origenId": "0015f00000X9OyaAAF",
      "nombre": "Droguería Alemana 109",
      "cadena": "",
      "ciudad": "IBAGUÉ",
      "brick": "5218",
      "brickZona": "IBAGUE",
      "direccion": "Carrera 6A #60-11 Local 106",
      "frecuencia": 1,
      "adium": false
    },
    {
      "origenId": "0015f00000X9OQ3AAN",
      "nombre": "Droguería Alemana 214",
      "cadena": "",
      "ciudad": "IBAGUÉ",
      "brick": "5218",
      "brickZona": "IBAGUE",
      "direccion": "Carrera 5 #62-90",
      "frecuencia": 1,
      "adium": false
    },
    {
      "origenId": "0015f00000X9P8PAAV",
      "nombre": "Droguería Alemana 222",
      "cadena": "",
      "ciudad": "IBAGUÉ",
      "brick": "5218",
      "brickZona": "IBAGUE",
      "direccion": "Carrera 5 #37B-03 Local 102 Santa Teresa",
      "frecuencia": 1,
      "adium": true
    },
    {
      "origenId": "0015f00000X9OQNAA3",
      "nombre": "Droguería Alemana 294",
      "cadena": "",
      "ciudad": "IBAGUÉ",
      "brick": "5218",
      "brickZona": "IBAGUE",
      "direccion": "Calle 60 #6-15",
      "frecuencia": 1,
      "adium": false
    },
    {
      "origenId": "001UR00000hlWjiYAE",
      "nombre": "Droguería Alemana 378",
      "cadena": "",
      "ciudad": "IBAGUÉ",
      "brick": "",
      "brickZona": "",
      "direccion": "Carrera 4 #4-11",
      "frecuencia": 1,
      "adium": true
    },
    {
      "origenId": "0015f00000X9P8tAAF",
      "nombre": "Droguería Alemana 76",
      "cadena": "",
      "ciudad": "BOGOTÁ",
      "brick": "9005",
      "brickZona": "CEDRITOS",
      "direccion": "Calle 140 #7C-57 Local 2",
      "frecuencia": 1,
      "adium": true
    },
    {
      "origenId": "0015f00000X9P8yAAF",
      "nombre": "Droguería Alemana 78",
      "cadena": "",
      "ciudad": "BOGOTÁ",
      "brick": "9005",
      "brickZona": "CEDRITOS",
      "direccion": "Calle 140 #12B-28",
      "frecuencia": 1,
      "adium": false
    },
    {
      "origenId": "0015f00000X9P9DAAV",
      "nombre": "Droguería Alemana 87",
      "cadena": "",
      "ciudad": "IBAGUÉ",
      "brick": "5218",
      "brickZona": "IBAGUE",
      "direccion": "Carrera 5 #37Bis-03 Local 109 Edificio Fontainebleau",
      "frecuencia": 1,
      "adium": false
    },
    {
      "origenId": "0015d00003ZsdI5AAJ",
      "nombre": "Droguería Audifarma Castellana",
      "cadena": "",
      "ciudad": "BOGOTÁ",
      "brick": "8824",
      "brickZona": "LA CASTELLANA",
      "direccion": "Autopista Norte Carrera 46 #93-59",
      "frecuencia": 1,
      "adium": true
    },
    {
      "origenId": "0015f00000X9NoeAAF",
      "nombre": "Droguería Cafam Bogotá Carulla Calle 140",
      "cadena": "",
      "ciudad": "BOGOTÁ",
      "brick": "9005",
      "brickZona": "CEDRITOS",
      "direccion": "Carrera 11 #140-29",
      "frecuencia": 1,
      "adium": true
    },
    {
      "origenId": "0015f00000X9P7hAAF",
      "nombre": "Droguería Cafam Bogotá Carulla Colina Campestre",
      "cadena": "",
      "ciudad": "BOGOTÁ",
      "brick": "9024",
      "brickZona": "CEDRITOS NORTE",
      "direccion": "Carrera 59A #136-95 Carulla Local 27B",
      "frecuencia": 1,
      "adium": false
    },
    {
      "origenId": "0015f00000X9ORKAA3",
      "nombre": "Droguería Cafam Bogotá Éxito Colina",
      "cadena": "",
      "ciudad": "BOGOTÁ",
      "brick": "9104",
      "brickZona": "LA COLINA",
      "direccion": "Avenida Carrera 72 #146-00",
      "frecuencia": 1,
      "adium": true
    },
    {
      "origenId": "0015f00000X9OVqAAN",
      "nombre": "Droguería Cafam Bogotá Éxito Country",
      "cadena": "",
      "ciudad": "BOGOTÁ",
      "brick": "9004",
      "brickZona": "CONTADOR",
      "direccion": "Calle 134 #9-51",
      "frecuencia": 1,
      "adium": false
    },
    {
      "origenId": "001UR00000o5YlqYAE",
      "nombre": "Droguería Cafam Centro de Experiencia Unicentro - Calle 119",
      "cadena": "",
      "ciudad": "BOGOTÁ",
      "brick": "",
      "brickZona": "",
      "direccion": "Carrera 13 #119-66",
      "frecuencia": 1,
      "adium": true
    },
    {
      "origenId": "0015f00000X9NNNAA3",
      "nombre": "Droguería Cafam Éxito Unicentro",
      "cadena": "",
      "ciudad": "BOGOTÁ",
      "brick": "9012",
      "brickZona": "SANTA BARBARA CENTRAL",
      "direccion": "Avenida 15 #123-30",
      "frecuencia": 1,
      "adium": false
    },
    {
      "origenId": "0015f00000Yb0IhAAJ",
      "nombre": "Droguería Colsubsidio Cardio Infantil",
      "cadena": "",
      "ciudad": "BOGOTÁ",
      "brick": "9009",
      "brickZona": "",
      "direccion": "Carrera 13B #161-8",
      "frecuencia": 1,
      "adium": false
    },
    {
      "origenId": "0015f00000X9OT9AAN",
      "nombre": "Droguería Colsubsidio Cedro",
      "cadena": "",
      "ciudad": "BOGOTÁ",
      "brick": "9005",
      "brickZona": "CEDRITOS",
      "direccion": "Calle 140 #10A-7",
      "frecuencia": 1,
      "adium": true
    },
    {
      "origenId": "0015f00000X9OyoAAF",
      "nombre": "Droguería Colsubsidio Centro Comercial Unicentro 2",
      "cadena": "",
      "ciudad": "BOGOTÁ",
      "brick": "9013",
      "brickZona": "SANTA BARBARA OCCIDENTAL",
      "direccion": "Avenida Carrera 15 #124-30",
      "frecuencia": 1,
      "adium": false
    },
    {
      "origenId": "0015d00003slcPmAAI",
      "nombre": "Droguería Colsubsidio Edificio Vanguardia",
      "cadena": "",
      "ciudad": "BOGOTÁ",
      "brick": "8810",
      "brickZona": "CHICO",
      "direccion": "Avenida Carrera 15 #100-67 Local 2",
      "frecuencia": 1,
      "adium": false
    },
    {
      "origenId": "0015f00000X9P9LAAV",
      "nombre": "Droguería Colsubsidio Palatino",
      "cadena": "",
      "ciudad": "BOGOTÁ",
      "brick": "",
      "brickZona": "",
      "direccion": "Carrera 7 #138-33 Local 124",
      "frecuencia": 1,
      "adium": true
    },
    {
      "origenId": "0015f00000X9P7ZAAV",
      "nombre": "Droguería Colsubsidio San Rafael",
      "cadena": "",
      "ciudad": "BOGOTÁ",
      "brick": "",
      "brickZona": "",
      "direccion": "Calle 134 #55-30 Local 212",
      "frecuencia": 1,
      "adium": true
    },
    {
      "origenId": "0015f00000X9PANAA3",
      "nombre": "Droguería Cruz Verde Acomédica",
      "cadena": "",
      "ciudad": "BOGOTÁ",
      "brick": "9019",
      "brickZona": "REINA SOFIA",
      "direccion": "Calle 127 #19A-28 Auditorio 1",
      "frecuencia": 1,
      "adium": true
    },
    {
      "origenId": "0015d000043MOQkAAO",
      "nombre": "Droguería Cruz Verde Calle 103",
      "cadena": "",
      "ciudad": "BOGOTÁ",
      "brick": "8815",
      "brickZona": "CHICO",
      "direccion": "Carrera 15 #103-31 Local 101",
      "frecuencia": 1,
      "adium": false
    },
    {
      "origenId": "0015f00000Ya9RVAAZ",
      "nombre": "Droguería Cruz Verde Calle 119",
      "cadena": "",
      "ciudad": "BOGOTÁ",
      "brick": "9012",
      "brickZona": "SANTA BARBARA CENTRAL",
      "direccion": "Calle 119 #12-36",
      "frecuencia": 1,
      "adium": false
    },
    {
      "origenId": "0015d00003k0FOrAAM",
      "nombre": "Droguería Cruz Verde Ecotower Navarra",
      "cadena": "",
      "ciudad": "BOGOTÁ",
      "brick": "8819",
      "brickZona": "CHICO TORRE ESPECIALISTAS",
      "direccion": "Avenida Calle 100 #23-10",
      "frecuencia": 1,
      "adium": false
    },
    {
      "origenId": "001UR00000dzeDRYAY",
      "nombre": "Drogueria Cruz Verde Medicarte Colina",
      "cadena": "",
      "ciudad": "BOGOTÁ",
      "brick": "",
      "brickZona": "",
      "direccion": "Carrera 58 #137-18 Locales 103 y 104",
      "frecuencia": 1,
      "adium": false
    },
    {
      "origenId": "0015d00003fYE1RAAW",
      "nombre": "Droguería Cruz Verde Montearroyo 2",
      "cadena": "",
      "ciudad": "BOGOTÁ",
      "brick": "9005",
      "brickZona": "CEDRITOS",
      "direccion": "Calle 140 #11-01 Local 101",
      "frecuencia": 1,
      "adium": false
    },
    {
      "origenId": "0015f00000X9PBAAA3",
      "nombre": "Droguería Cruz Verde Montearroyo Principal",
      "cadena": "",
      "ciudad": "BOGOTÁ",
      "brick": "9006",
      "brickZona": "CEDRITOS 2",
      "direccion": "Calle 147 #13-07",
      "frecuencia": 1,
      "adium": false
    },
    {
      "origenId": "0015f00000YbLraAAF",
      "nombre": "Droguería Cruz Verde Punto 100",
      "cadena": "",
      "ciudad": "BOGOTÁ",
      "brick": "8815",
      "brickZona": "CHICO",
      "direccion": "Calle 100 #19-61",
      "frecuencia": 1,
      "adium": false
    },
    {
      "origenId": "001UR00000dzjPxYAI",
      "nombre": "Droguería Cruz Verde Punto Cero",
      "cadena": "",
      "ciudad": "IBAGUÉ",
      "brick": "",
      "brickZona": "",
      "direccion": "Carrera 5 #43-11 Local 2",
      "frecuencia": 1,
      "adium": false
    },
    {
      "origenId": "001UR00000pQYQUYA4",
      "nombre": "Droguería Cruz Verde San Patricio",
      "cadena": "",
      "ciudad": "BOGOTÁ",
      "brick": "",
      "brickZona": "",
      "direccion": "Calle 109 #18C-17 - Local 4",
      "frecuencia": 1,
      "adium": false
    },
    {
      "origenId": "0015f00000X9NMiAAN",
      "nombre": "Droguería Cruz Verde Uap Ibagué",
      "cadena": "",
      "ciudad": "IBAGUÉ",
      "brick": "5218",
      "brickZona": "IBAGUE",
      "direccion": "Avenida Mirolindo #44-233",
      "frecuencia": 1,
      "adium": true
    },
    {
      "origenId": "0015d00003fXXvdAAG",
      "nombre": "Droguería Cruz Verde Unicentro Bogotá",
      "cadena": "",
      "ciudad": "BOGOTÁ",
      "brick": "9012",
      "brickZona": "SANTA BARBARA CENTRAL",
      "direccion": "Avenida Carrera 15 #124-30 Local 2-83 Centro Comercial Unicentro",
      "frecuencia": 1,
      "adium": false
    },
    {
      "origenId": "0015d00003bnjSIAAY",
      "nombre": "Droguería Drogas La Rebaja 4",
      "cadena": "",
      "ciudad": "IBAGUÉ",
      "brick": "5221",
      "brickZona": "IBAGUE",
      "direccion": "Carrera 3 #12-02",
      "frecuencia": 1,
      "adium": false
    },
    {
      "origenId": "001UR00000o5LDWYA2",
      "nombre": "Droguería Farmacádiz La Samaria - Coopidrogas",
      "cadena": "",
      "ciudad": "IBAGUÉ",
      "brick": "",
      "brickZona": "",
      "direccion": "Carrera 12 Sur #93 -21 Local 5 Clínica Medicadiz",
      "frecuencia": 1,
      "adium": true
    },
    {
      "origenId": "0015d00003fYAN7AAO",
      "nombre": "Droguería Farmatodo Belmira",
      "cadena": "",
      "ciudad": "BOGOTÁ",
      "brick": "9005",
      "brickZona": "CEDRITOS",
      "direccion": "Avenida Carrera 9 #139-88",
      "frecuencia": 1,
      "adium": false
    },
    {
      "origenId": "0015f00000X9PBOAA3",
      "nombre": "Droguería Farmatodo Calle 119",
      "cadena": "",
      "ciudad": "BOGOTÁ",
      "brick": "9012",
      "brickZona": "SANTA BARBARA CENTRAL",
      "direccion": "Calle 119 #13-15",
      "frecuencia": 1,
      "adium": false
    },
    {
      "origenId": "0015f00000X9OWMAA3",
      "nombre": "Droguería Farmatodo Calle 127",
      "cadena": "",
      "ciudad": "BOGOTÁ",
      "brick": "9019",
      "brickZona": "REINA SOFIA",
      "direccion": "Avenida Calle 127 #17A-27",
      "frecuencia": 1,
      "adium": true
    },
    {
      "origenId": "0015f00000X9NhQAAV",
      "nombre": "Droguería Farmatodo Calle 147",
      "cadena": "",
      "ciudad": "BOGOTÁ",
      "brick": "9025",
      "brickZona": "CEDRITOS-COLINA",
      "direccion": "Avenida Carrera 19 #146-81",
      "frecuencia": 1,
      "adium": false
    },
    {
      "origenId": "0015d00003ygFVoAAM",
      "nombre": "Droguería Farmatodo Calleja",
      "cadena": "",
      "ciudad": "BOGOTÁ",
      "brick": "9019",
      "brickZona": "REINA SOFIA",
      "direccion": "Avenida Carrera 19 #127-53",
      "frecuencia": 1,
      "adium": false
    },
    {
      "origenId": "0015f00000X9PBbAAN",
      "nombre": "Droguería Farmatodo CC Unicentro",
      "cadena": "",
      "ciudad": "BOGOTÁ",
      "brick": "9012",
      "brickZona": "SANTA BARBARA CENTRAL",
      "direccion": "Avenida 15 #123-30 - Local 2-45",
      "frecuencia": 1,
      "adium": false
    },
    {
      "origenId": "0015f00000X9OiVAAV",
      "nombre": "Droguería Farmatodo Cedritos 2",
      "cadena": "",
      "ciudad": "BOGOTÁ",
      "brick": "9005",
      "brickZona": "CEDRITOS",
      "direccion": "Calle 140 #13-27",
      "frecuencia": 1,
      "adium": false
    },
    {
      "origenId": "0015f00000X9OiZAAV",
      "nombre": "Droguería Farmatodo Colina",
      "cadena": "",
      "ciudad": "BOGOTÁ",
      "brick": "9104",
      "brickZona": "LA COLINA",
      "direccion": "Calle 138 #59-23 Esquina Avenida Boyacá",
      "frecuencia": 1,
      "adium": true
    },
    {
      "origenId": "0015f00000X9OiaAAF",
      "nombre": "Droguería Farmatodo Cosmos 100",
      "cadena": "",
      "ciudad": "BOGOTÁ",
      "brick": "8819",
      "brickZona": "CHICO TORRE ESPECIALISTAS",
      "direccion": "Transversal 21 #98-71 - Local 101",
      "frecuencia": 1,
      "adium": true
    },
    {
      "origenId": "0015f00000X9OyYAAV",
      "nombre": "Droguería Farmatodo Country",
      "cadena": "",
      "ciudad": "BOGOTÁ",
      "brick": "8809",
      "brickZona": "CHICO COLSANITAS",
      "direccion": "Carrera 15 #94-72",
      "frecuencia": 1,
      "adium": false
    },
    {
      "origenId": "0015f00000X9OWSAA3",
      "nombre": "Droguería Farmatodo Navarra",
      "cadena": "",
      "ciudad": "BOGOTÁ",
      "brick": "8815",
      "brickZona": "CHICO",
      "direccion": "Avenida Carrera 19 #103-98",
      "frecuencia": 1,
      "adium": false
    },
    {
      "origenId": "0015f00000X9OWVAA3",
      "nombre": "Droguería Farmatodo Rincón Del Chico",
      "cadena": "",
      "ciudad": "BOGOTÁ",
      "brick": "8811",
      "brickZona": "RINCON DEL CHICO",
      "direccion": "Avenida 15 #106-18 - Local 1",
      "frecuencia": 1,
      "adium": false
    },
    {
      "origenId": "0015f00000X9ON1AAN",
      "nombre": "Droguería La Rebaja 104 Bogotá Cedritos 2",
      "cadena": "",
      "ciudad": "BOGOTÁ",
      "brick": "",
      "brickZona": "",
      "direccion": "Calle 147 #7-58 Local 26",
      "frecuencia": 1,
      "adium": false
    },
    {
      "origenId": "0015d00003slcTOAAY",
      "nombre": "Droguería La Rebaja 125 Bogotá Santa Paula 1",
      "cadena": "",
      "ciudad": "BOGOTÁ",
      "brick": "8811",
      "brickZona": "RINCON DEL CHICO",
      "direccion": "Avenida 15 #105-16",
      "frecuencia": 1,
      "adium": false
    },
    {
      "origenId": "0015f00000X9ON8AAN",
      "nombre": "Droguería La Rebaja 65 Bogotá Colina Campestre",
      "cadena": "",
      "ciudad": "BOGOTÁ",
      "brick": "",
      "brickZona": "",
      "direccion": "Carrera 58 #137B-38 Local 101",
      "frecuencia": 1,
      "adium": false
    },
    {
      "origenId": "0015f00000X9ONFAA3",
      "nombre": "Droguería La Rebaja 67 Bogotá El Bosque",
      "cadena": "",
      "ciudad": "BOGOTÁ",
      "brick": "",
      "brickZona": "",
      "direccion": "Calle 134 #7B-83 Local 18",
      "frecuencia": 1,
      "adium": false
    },
    {
      "origenId": "0015f00000X9ONkAAN",
      "nombre": "Droguería La Rebaja Plus 1 Bogotá Colina Calle 137",
      "cadena": "",
      "ciudad": "BOGOTÁ",
      "brick": "9023",
      "brickZona": "",
      "direccion": "Carrera 58 #137A-30",
      "frecuencia": 1,
      "adium": false
    },
    {
      "origenId": "0015f00000X9OO3AAN",
      "nombre": "Droguería La Rebaja Plus 1 Ibagué Frente A Bancolombia",
      "cadena": "",
      "ciudad": "IBAGUÉ",
      "brick": "",
      "brickZona": "",
      "direccion": "Carrera 3 #14-47",
      "frecuencia": 1,
      "adium": false
    },
    {
      "origenId": "0015f00000X9OONAA3",
      "nombre": "Droguería La Rebaja Plus 3 Ibagué San Simon",
      "cadena": "",
      "ciudad": "IBAGUÉ",
      "brick": "5218",
      "brickZona": "IBAGUE",
      "direccion": "Carrera 5 #36-25",
      "frecuencia": 1,
      "adium": false
    },
    {
      "origenId": "0015f00000X9OOTAA3",
      "nombre": "Droguería La Rebaja Plus 4 Ibagué El Limonar",
      "cadena": "",
      "ciudad": "IBAGUÉ",
      "brick": "5218",
      "brickZona": "IBAGUE",
      "direccion": "Carrera 6 #59-25",
      "frecuencia": 1,
      "adium": false
    },
    {
      "origenId": "0015f00000X9OMbAAN",
      "nombre": "Droguería La Rebaja Plus 63 Bogotá Calle 119",
      "cadena": "",
      "ciudad": "BOGOTÁ",
      "brick": "",
      "brickZona": "",
      "direccion": "Calle 119 #12-39",
      "frecuencia": 1,
      "adium": false
    },
    {
      "origenId": "0015d00003bkrWRAAY",
      "nombre": "Droguería Olímpica Calle 100",
      "cadena": "",
      "ciudad": "BOGOTÁ",
      "brick": "8824",
      "brickZona": "LA CASTELLANA",
      "direccion": "Calle 100 #30-77",
      "frecuencia": 1,
      "adium": false
    },
    {
      "origenId": "0015f00000X9ObxAAF",
      "nombre": "Droguería Olímpica Sto 418 Colina Campestre",
      "cadena": "",
      "ciudad": "BOGOTÁ",
      "brick": "9024",
      "brickZona": "CEDRITOS NORTE",
      "direccion": "Calle 138 #52-03 Centro Comercial Porto Alegre",
      "frecuencia": 1,
      "adium": false
    },
    {
      "origenId": "0015d00003ygdppAAA",
      "nombre": "Droguería Optimo Lh",
      "cadena": "",
      "ciudad": "IBAGUÉ",
      "brick": "5219",
      "brickZona": "IBAGUE",
      "direccion": "Carrera 5 #71-52",
      "frecuencia": 1,
      "adium": true
    }
  ]
};

async function cargarPanelLocal() {
  await db.reemplazarMedicos(PANEL_DATA.medicos);
  await db.reemplazarFarmacias(PANEL_DATA.farmacias);
  await db.setConfig('lastSync', new Date().toISOString());
}

async function procesarExcelFile(arrayBuffer) {
  const xlsx = window.XLSX;
  const wb = xlsx.read(new Uint8Array(arrayBuffer), {type: 'array'});
  const medSheet = wb.Sheets['Medicos'];
  const farmSheet = wb.Sheets['Farmacias'];
  const medRows = xlsx.utils.sheet_to_json(medSheet, {header:1}).slice(1);
  const farmRows = farmSheet ? xlsx.utils.sheet_to_json(farmSheet, {header:1}).slice(1) : [];
  
  const meds = medRows.map((r, i) => {
    const nombre = (r[2] || '').toString().trim();
    if (!nombre) return null;
    const medicoH = (r[5] || '').toString().trim().toUpperCase();
    const segLinea = (r[7] || '').toString().trim();
    const segs = [];
    if (medicoH === 'SI') segs.push('H');
    const v = segLinea.toUpperCase().trim();
    if (v === 'PS' || v === 'POR SEGMENTAR') segs.push('PS');
    if (v === 'EVALUAR') segs.push('E');
    if (v === 'CONQUISTAR') segs.push('C');
    if (v === 'MANTENER') segs.push('M');
    if (v === 'PROTEGER') segs.push('P');
    const brickNum = (r[10] || '').toString().trim();
    const comarketing = (r[14] || '').toString().trim().toLowerCase();
    return {
      origenId: (r[0] || String(i)).toString().trim(),
      nombre,
      especialidad: (r[3] || '').toString().trim(),
      segmento: segs.join(','),
      frecuencia: parseInt(r[6]) || 1,
      ciudad: (r[8] || '').toString().trim().toUpperCase(),
      brick: brickNum,
      brickZona: getBrickZona(brickNum),
      direccion: (r[9] || '').toString().trim(),
      celular: (r[11] || '').toString().trim(),
      email: (r[12] || '').toString().trim(),
      deblax: comarketing === 'deblax'
    };
  }).filter(Boolean);
  
  const farms = farmRows.map((r, i) => {
    const nombre = (r[1] || '').toString().trim();
    if (!nombre) return null;
    const brickNum = (r[5] || '').toString().trim();
    return {
      origenId: (r[0] || String(i)).toString().trim(),
      nombre,
      cadena: '',
      ciudad: (r[3] || '').toString().trim().toUpperCase(),
      brick: brickNum,
      brickZona: getBrickZona(brickNum),
      direccion: (r[4] || '').toString().trim(),
      frecuencia: parseInt(r[2]) || 1,
      adium: typeof esFarmaciaAdium === 'function' ? esFarmaciaAdium(nombre) : false
    };
  }).filter(Boolean);
  
  await db.reemplazarMedicos(meds);
  await db.reemplazarFarmacias(farms);
  await db.setConfig('lastSync', new Date().toISOString());
  return {medicos: meds.length, farmacias: farms.length};
}
